### ISSUE TITLE
Transmit call fails when size is > 12

### ISSUE THREAD

**Issue by srobins6** [Pulse-Eight/libcec#443]
In LibCecSharp the Transit function fails when command.Parameters.Size > 12

**Comment by malard** [comment]
maximum length for cec spec is this, we can put a guard to help developers

**Comment by srobins6** [comment]
Where are you getting the maximum number? All the documentation I can find says it's 16, not 12.

**Comment by malard** [comment]
the first 4 are taken by transmission data, @opdenkamp will confirm my thoughts

**Comment by srobins6** [comment]
thank you!

**Comment by srobins6** [comment]
Does the "Initiator" value which I believe takes up 2 bytes at the start tell the adapter which of potentially multiple hdmi connections to use?

**Comment by srobins6** [comment]
Can you elaborate on what specific information those 4 bytes represent?

**Comment by opdenkamp** [comment]
Hi @srobins6 , I've responded to your question in the email to you've sent. You can send 16 bytes of data, 2 of which are taken by the header (initiator, destination, opcode). I've verified that this is working correctly on libCEC 4.0.2+

There was a bug in an old version of libCEC which prevented the last bytes from being sent, which has been fixed. If it's not working for you, then you may have to upgrade: https://github.com/Pulse-Eight/libcec/releases/tag/libcec-4.0.3

**Comment by srobins6** [comment]
I am still having this issue with libcecsharp specifically, haven't tested with other libraries

**Comment by opdenkamp** [comment]
I have tested sending a 16 byte packet with CecSharpTester: https://github.com/Pulse-Eight/cec-dotnet/tree/180cbe2b4e2b2d6a58c4b22d09760aba4b67a8e5/src/CecSharpTester
It was received correctly by another CEC adapter on which I was running cec-client.

Have you upgraded to the latest version?

**Comment by opdenkamp** [comment]
Updating the status here too: this is caused by a bug in the firmware on the TX side, which results in TRANSMIT_FAILED_TIMEOUT_DATA when attempting to send out a 16 byte packet.

**Comment by opdenkamp** [comment]
This isn't caused by the firmware after all, but was caused by a buffer that couldn't fit this.
